version: "3"
services:
  mongo:
    image: mongo
    hostname: localhost
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    container_name: my_mongo

