mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.nkcoder.mybatis.xml.entity;