version: '3.1'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.248.69
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    depends_on:
      - zookeeper

  web:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - kafka

networks:
  backend: