# ssl config: pkcs12 format
server:
  port: 8443
  ssl:
    key-store: classpath:keystore/mykeys.p12
    key-store-password: admin123
    key-password: admin123
    key-store-type: PKCS12
    key-alias: mykeys