management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
        exclude: heapdump,threaddump

  endpoint:
    health:
      show-details: always

  info:
    git:
      mode: full

# for endpoint: /actuator/info
info:
  contact:
    email: myeamil@example.com
    phone: +86-17100000000

