version: "3.1"
services:
  rabbitmq:
    image: "rabbitmq:3.8-rc-management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      name: "my-rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "rabbit-pass"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - rabbitmq

networks:
  backend:
