version: "3"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: local
    container_name: devtools-1
