server:
  port: 9090

spring:
  boot:
    admin:
      client:
        url: http://localhost:9090

  application:
    name: spring-boot-admin-server

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
        exclude: heapdump
